### ISSUE TITLE
CompanionDeviceManager crash

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/Meshrabiya#1]
Observed on Lenovo TB-7306F running Android 11
```
                        I  setInputWindows displayId=0 Window{a04930a u0 NavigationBar0} Window{1b88c3f u0 StatusBar} com.android.companiondevicemanager/com.android.companiondevicemanager.DeviceChooserActivity#0 Window{7efd62b u0 com.ustadmobile.test_app/com.ustadmobile.test_app.VNetTestActivity} Window{9b0a507 u0 com.android.systemui.ImageWallpaper} 
2023-06-16 16:51:45.999   889-1048  bt_btif_config          com.android.bluetooth                D  btif_get_device_type: Device [e0:51:d3:42:8e:8b] type 2
--------- beginning of crash
2023-06-16 16:51:46.001 13967-13967 AndroidRuntime          com.android.companiondevicemanager   D  Shutting down VM
2023-06-16 16:51:46.002 13967-13967 AndroidRuntime          com.android.companiondevicemanager   E  FATAL EXCEPTION: main
                                                                                                    Process: com.android.companiondevicemanager, PID: 13967
                                                                                                    java.lang.NullPointerException
                                                                                                    	at com.android.internal.util.AnnotationValidations.validate(AnnotationValidations.java:129)
                                                                                                    	at android.companion.Association.<init>(Association.java:66)
                                                                                                    	at com.android.companiondevicemanager.DeviceDiscoveryService.onDeviceSelected(DeviceDiscoveryService.java:307)
                                                                                                    	at com.android.companiondevicemanager.DeviceChooserActivity.onDeviceConfirmed(DeviceChooserActivity.java:158)
                                                                                                    	at com.android.companiondevicemanager.DeviceChooserActivity.onSelectionUpdate(DeviceChooserActivity.java:147)
                                                                                                    	at com.android.companiondevicemanager.DeviceChooserActivity.access$000(DeviceChooserActivity.java:40)
                                                                                                    	at com.android.companiondevicemanager.DeviceChooserActivity$1.onChanged(DeviceChooserActivity.java:85)
                                                                                                    	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
                                                                                                    	at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:54)
                                                                                                    	at android.widget.ArrayAdapter.notifyDataSetChanged(ArrayAdapter.java:355)
                                                                                                    	at com.android.companiondevicemanager.DeviceDiscoveryService.onDeviceFoundMainThread(DeviceDiscoveryService.java:278)
                                                                                                    	at com.android.companiondevicemanager.-$$Lambda$FF3bv59uzMtgFDQgbuOHg5xdwqo.accept(Unknown Source:4)
                                                                                                    	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:278)
                                                                                                    	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
                                                                                                    	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7709)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
2023-06-16 16:51:46.004   710-5971  InputDispatcher         system_server                        I  setInputWindows displayId=0 Window{a04930a u0 NavigationBar0} Window{1b88c3f u0 StatusBar} com.android.companiondevicemanager/com.android.companiondevicemanager.DeviceChooserActivity#0 Window{7efd62b u0 com.ustadmobile.test_app/com.ustadmobile.test_app.VNetTestActivity} Window{9b0a507 u0 com.android.systemui.ImageWallpaper} 
2023-06-16 16:51:46.006   387-449   libPowerHal             ven...hardware.mtkpower@1.0-service  I  [perfNotifyAppState] pack:com.android.companiondevicemanager, pid:13967, STATE_DEAD
2023-06-16 16:51:46.006   387-449   RilUtility              ven...hardware.mtkpower@1.0-service  D  notify_rild_crash_pid_set certPid:-1, crash:13967, scn:0x0
2023-06-16 16:51:46.007   889-1048  bt_btif_config          com.android.bluetooth                D  btif_get_device_type: Device [6b:2c:cc:41:05:f5] t
```

![WhatsApp Image 2023-06-16 at 15 08 42](https://github.com/UstadMobile/HttpOverBluetooth/assets/4280622/ec2ec5c0-f879-4420-88e5-96d51582b619)

**Comment by mikedawson** [comment]
Obsolete - we are no longer using CompanionDeviceManager
